#!/bin/sh

### BEGIN INIT INFO
# Provides:           planets_production
# Required-Start:     $local_fs $remote_fs $network $syslog
# Required-Stop:      $local_fs $remote_fs $network $syslog
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  starts planets_production (a rails app)
# Description:        starts planets_production (a rails app) using start-stop-daemon
### END INIT INFO

USER=wataru
APP_ROOT=/var/rails/planets_production/current
RAILS_ENV=production
PID_FILE=$APP_ROOT/tmp/pids/unicorn.pid
CONFIG_FILE=$APP_ROOT/config/unicorn/production.rb
CMD="/usr/local/bin/bundle exec /usr/local/bin/unicorn_rails"
ARGS="-c $CONFIG_FILE -D -E $RAILS_ENV"

export PATH=/usr/local/bin:$PATH

case $1 in
  start)
    start-stop-daemon --start --chuid $USER --chdir $APP_ROOT \
      --exec $CMD -- $ARGS || true
    ;;
  stop)
    start-stop-daemon --stop --signal QUIT --pidfile $PID_FILE || true
    ;;
   ;;
  restart|force-reload)
    start-stop-daemon --stop --signal USR2 --pidfile $PID_FILE || true
    ;;
  status)
    status_of_proc -p $PID_FILE "$CMD" planets_production && exit 0 || exit $?
    ;;
  *)
    echo >&2 "Usage: $0 <start|stop|restart|force-reload|status>"
    exit 1
    ;;
esac